apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: shital37/my-order-processing:latest
        ports:
        - containerPort: 80
